export const MENU_CLICKED = 'MENU_CLICKED'
export const STORE_INITIALIZE = 'STORE_INITIALIZE'

export const SET_WAS_BUILDING_TRUE ='SET_WAS_BUILDING_TRUE'
export const SET_WAS_BUILDING_FALSE ='SET_WAS_BUILDING_FALSE'


export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED'
export const GET_ORDERS_START = 'GET_ORDERS_START'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_CLEANUP_ERROR = 'AUTH_CLEANUP_ERROR'

export const GET_USER_INFO_START ='GET_USER_INFO_START'
export const GET_USER_INFO_FAILED ='GET_USER_INFO_FAILED'
export const GET_USER_INFO_SUCCESS ='GET_USER_INFO_SUCCESS'

export const SET_DIFF_ADDR ='SET_DIFF_ADDR'


